general.import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-mocha.toml",
]


[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
style = "Bold"
family = "JetBrainsMono Nerd Font Mono"

[font.bold_italic]
style = "Bold Italic"
family = "JetBrainsMono Nerd Font Mono"


[font.italic]
style = "Italic"
family = "JetBrainsMono Nerd Font Mono"


[font.normal]
style = "Regular"
family = "JetBrainsMono Nerd Font Mono"


[window]
opacity = 0.8
blur = false
