general.import = ["~/.config/alacritty/vesper.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 1

[font]
size = 14.0


[font.bold]
style = "Bold"
family = "JetBrainsMono Nerd Font Mono"

[font.bold_italic]
style = "Bold Italic"
family = "JetBrainsMono Nerd Font Mono"




[font.italic]
style = "Italic"
family = "JetBrainsMono Nerd Font Mono"




[font.normal]
style = "Regular"
family = "JetBrainsMono Nerd Font Mono"




