
# Application bindings
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

# Voice Dictation
bindd = SUPER SHIFT, D, Voice Dictation, exec, bash /home/aarsh/.local/bin/hyprwhisper

bindd = SUPER, N, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER, B, Browser, exec, helium-browser
bindd = SUPER SHIFT, B, Browser (private), exec, $browser --private
bindd = SUPER, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER, G, Telegram-Desktop, exec,telegram-desktop
bind = SUPER, Q, killactive

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER SHIFT, A, Perplexity, exec, omarchy-launch-webapp "https://www.perplexity.ai/"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"

unbind = SUPER, K
unbind = SUPER, W
unbind = SUPER, J
unbind = SUPER, F

unbind = SUPER, S


bindd = ALT, SPACE, Clipboard manager, exec, omarchy-launch-walker -m clipboard

bind = SUPER, RETURN, fullscreen, 0


# Focus movement with HJKL
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

# Move window with SUPER + Shift + arrow keys
bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, L, movewindow, r
bind = SUPER SHIFT, K , movewindow, u
bind = SUPER SHIFT, J, movewindow, d

bind = CTRL SUPER, L, resizeactive, 50 0
bind = CTRL SUPER, H, resizeactive, -50 0
bind = CTRL SUPER, J, resizeactive, 0 50
bind = CTRL SUPER, K, resizeactive, 0 -50

bind = SUPER, S, togglespecialworkspace,
bind = SUPER SHIFT, S, movetoworkspace, special


bind = SUPER, 0, workspace, 10
bind = SUPER SHIFT, 0, movetoworkspace, 10


# Alternative suggestions
bindd = SUPER, I, Toggle split, layoutmsg, togglesplit # I for "interchange"
bindd = SUPER, F, Toggle floating, togglefloating, # R for "release" from tiling
# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu


# Screenshots
bindd = , F9, Screenshot of region, exec, omarchy-cmd-screenshot
bindd = SHIFT, F9, Screenshot of window, exec, omarchy-cmd-screenshot window
bindd = CTRL, F9, Screenshot of display, exec, omarchy-cmd-screenshot output

# Screen recordings  
bindd = ALT, F9, Screen record a region, exec, omarchy-cmd-screenrecord region
bindd = ALT SHIFT, F9, Screen record a region with audio, exec, omarchy-cmd-screenrecord region audio
bindd = CTRL ALT, F9, Screen record display, exec, omarchy-cmd-screenrecord output
bindd = CTRL ALT SHIFT, F9, Screen record display with audio, exec, omarchy-cmd-screenrecord output audio

# Color picker
bindd = SUPER, F9, Color picker, exec, pkill hyprpicker || hyprpicker -a
bindd = SUPER SHIFT, T, Tema, exec, uwsm app -- tema


bind = SUPER, F5, exec, playerctl previous

bind = SUPER, F6, exec, playerctl play-pause

bind = SUPER, F7, exec, playerctl next
