# Assign applications to workspaces
#windowrulev2 = workspace 1, class:(librewolf)
#windowrulev2 = workspace 2, class:(kitty)

# Windows opacity

# Windows tiling

# Prevent suspend when a fullscreen app is open
windowrulev2 = idleinhibit fullscreen, class:^(*)$
windowrulev2 = idleinhibit fullscreen, title:^(*)$
windowrulev2 = idleinhibit fullscreen, fullscreen:1
#
# # Smart gaps
# workspace = w[tv1]s[false], gapsout:0, gapsin:0
# workspace = f[1]s[false], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]s[false]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]s[false]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]s[false]
# windowrule = rounding 0, floating:0, onworkspace:f[1]s[false]
